[package]
name = "poogie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = "0.37"
anyhow = "1.0.57"
log = "0.4.17"
env_logger = "0.9.0"